trigger:
  batch: true
  branches:
    exclude:
    - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '7'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSLibraryBuild'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-library/build'
    OverWrite: true

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm install
  displayName: 'Npm install survey-creator'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages/survey-knockout'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator/node_modules/survey-knockout'
    OverWrite: true

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
    npm install
    npm run remove-package-lock
  displayName: 'Npm install survey-creator-core'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
    npm run build
  displayName: 'Build creator v2 core'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
    npm install
    npm run remove-package-lock
  displayName: 'Npm install survey-creator-knockout'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    npm install
    npm run remove-package-lock
  displayName: 'Npm install survey-creator-react'

# Creator CORE
- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
    npm run build
  displayName: 'Build creator v2 core'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
    npm run test
  displayName: 'Unit tests creator v2 core'
  

# Creator REACT
- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types
    ls
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types/react
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types/react
    ls
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types/react-dom
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/@types/react-dom
    ls
    cd $(Build.SourcesDirectory)/survey-library/build
    echo $(Build.SourcesDirectory)/survey-library/build
    ls
    cd $(Build.SourcesDirectory)/survey-library/build/survey-core
    echo $(Build.SourcesDirectory)/survey-library/build/survey-core
    ls
    cd $(Build.SourcesDirectory)/survey-library/build/survey-react-ui
    echo $(Build.SourcesDirectory)/survey-library/build/survey-react-ui
    ls
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-core
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-core
    ls
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-react-ui
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-react-ui
    ls
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    echo $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    ls
  displayName: 'Pre-debug survey-creator-react build'

# copy survey-core and survey-ui builds from the latest library build to creator-kncokout and creator-react node_modules for f-f tests
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-core'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-core'
    OverWrite: true
  displayName: 'copy build from library for f-f tests'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-react-ui'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react/node_modules/survey-react-ui'
    OverWrite: true
  displayName: 'copy build from library for f-f tests'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-core'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/node_modules/survey-core'
    OverWrite: true
  displayName: 'copy build from library for f-f tests'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-knockout-ui'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/node_modules/survey-knockout-ui'
    OverWrite: true
  displayName: 'copy build from library for f-f tests'

# EO copy for f-f tests
- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    npm run build
  displayName: 'Build creator v2 react'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    npm run test
  displayName: 'Unit tests creator v2 react'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-react
    npm run testcafe:ci
  displayName: 'Functional tests creator v2 react'


# Creator KNOCKOUT

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
    npm run build
  displayName: 'Build creator v2 knockout'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
    npm run test
  displayName: 'Unit tests creator v2 knockout'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
    npm run testcafe:ci
  displayName: 'Functional tests creator v2 knockout'


# Creator V1
- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm run build_prod
  displayName: 'Build prod'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm run test_ci
  displayName: 'Unit tests'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm run testcafe_ci
  displayName: 'Functional tests'