trigger:
  batch: true
  branches:
    exclude:
    - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '7'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSLibraryBuild'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-library/build'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages/survey-knockout'
    Contents: '**'
    TargetFolder: 'packages/survey-creator/node_modules/survey-knockout'
    OverWrite: true

- script: |
    cd packages/survey-creator
    npm install
  displayName: 'Npm install survey-creator'

- script: |
    cd packages/survey-creator-core
    npm install
    npm run remove-package-lock
  displayName: 'Npm install survey-creator-core'

- script: |
    cd packages/survey-creator-core
    npm run build
  displayName: 'Build creator v2 core'

- script: |
    cd packages/survey-creator-knockout
    npm install
    npm run remove-package-lock
  displayName: 'Npm install survey-creator-knockout'

- script: |
    cd packages/survey-creator-react
    npm install
    npm run remove-package-lock
  displayName: 'Npm install survey-creator-react'

# npm run release with version
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/'
    Contents: 'version.txt'
    TargetFolder: '$(Build.SourcesDirectory)/'
    OverWrite: true
  displayName: 'Copy build artifact - SurveyJSVersion File'

- powershell: |
    $version = Get-Content $(Build.SourcesDirectory)/version.txt
    Write-Host "##vso[task.setvariable variable=SurveyJSVersion;]$version"
  displayName: 'Setup SurveyJSVersion variable from SurveyJSVersionFile'

- powershell: |
    cd packages/survey-creator
    npm run release -- --release-as $(SurveyJSVersion)
  displayName: 'Release specific version survey-creator'
#####################################################

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '42'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSWidgetsBuild'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSWidgetsBuild/packages/survey-widgets'
    Contents: '**'
    TargetFolder: 'packages/survey-creator/node_modules/surveyjs-widgets'
    OverWrite: true

# Creator CORE
- powershell: |
    cd packages/survey-creator-core
    npm run release
  displayName: 'Release specific version survey-creator-core'

- script: |
    cd packages/survey-creator-core
    npm run build
  displayName: 'Build creator v2 core'

- script: |
    cd packages/survey-creator-core
    npm run test
  displayName: 'Unit tests creator v2 core'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: 'packages/survey-creator-core/build'
    targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-core


# Creator REACT
- script: |
    cd packages/survey-creator-react/node_modules/@types
    echo packages/survey-creator-react/node_modules/@types
    ls
    cd packages/survey-creator-react/node_modules/@types/react
    echo packages/survey-creator-react/node_modules/@types/react
    ls
    cd packages/survey-creator-react/node_modules/@types/react-dom
    echo packages/survey-creator-react/node_modules/@types/react-dom
    ls
    cd $(Build.SourcesDirectory)/survey-library/build
    echo $(Build.SourcesDirectory)/survey-library/build
    ls
    cd $(Build.SourcesDirectory)/survey-library/build/survey-core
    echo $(Build.SourcesDirectory)/survey-library/build/survey-core
    ls
    cd $(Build.SourcesDirectory)/survey-library/build/survey-react-ui
    echo $(Build.SourcesDirectory)/survey-library/build/survey-react-ui
    ls
    cd packages/survey-creator-react/node_modules/survey-core
    echo packages/survey-creator-react/node_modules/survey-core
    ls
    cd packages/survey-creator-react/node_modules/survey-react-ui
    echo packages/survey-creator-react/node_modules/survey-react-ui
    ls
    cd packages/survey-creator-react
    echo packages/survey-creator-react
    ls
  displayName: 'Pre-debug survey-creator-react build'

# copy survey-core and survey-ui builds from the latest library build to creator-kncokout and creator-react node_modules for f-f tests
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-core'
    Contents: '**'
    TargetFolder: 'packages/survey-creator-react/node_modules/survey-core'
    OverWrite: true
  displayName: 'copy build from library for f-f tests'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-react-ui'
    Contents: '**'
    TargetFolder: 'packages/survey-creator-react/node_modules/survey-react-ui'
    OverWrite: true
  displayName: 'copy build from library for f-f tests'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-core'
    Contents: '**'
    TargetFolder: 'packages/survey-creator-knockout/node_modules/survey-core'
    OverWrite: true
  displayName: 'copy build from library for f-f tests'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-knockout-ui'
    Contents: '**'
    TargetFolder: 'packages/survey-creator-knockout/node_modules/survey-knockout-ui'
    OverWrite: true
  displayName: 'copy build from library for f-f tests'

# EO copy for f-f tests
- powershell: |
    cd packages/survey-creator-react
    npm run release
  displayName: 'Release specific version survey-creator-react'

- script: |
    cd packages/survey-creator-react
    npm run build
  displayName: 'Build creator v2 react'

- script: |
    cd packages/survey-creator-react
    npm run test
  displayName: 'Unit tests creator v2 react'

- script: |
    cd packages/survey-creator-react
    npm run testcafe:ci
  displayName: 'Functional tests creator v2 react'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'packages/survey-creator-react/build'
    targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-react


# Creator KNOCKOUT
- powershell: |
    cd packages/survey-creator-knockout
    npm run release
  displayName: 'Release specific version survey-creator-knockout'

- script: |
    cd packages/survey-creator-knockout
    npm run build
  displayName: 'Build creator v2 knockout'

- script: |
    cd packages/survey-creator-knockout
    npm run test
  displayName: 'Unit tests creator v2 knockout'

- script: |
    cd packages/survey-creator-knockout
    npm run testcafe:ci
  displayName: 'Functional tests creator v2 knockout'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'packages/survey-creator-knockout/build'
    targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-knockout



# Creator V1
- script: |
    cd packages/survey-creator
    npm run build_prod
  displayName: 'Build prod'

- script: |
    cd packages/survey-creator
    npm run test_ci
  displayName: 'Unit tests'

- script: |
    cd packages/survey-creator
    npm run testcafe_ci
  displayName: 'Functional tests'

- script: |
    mkdir packages/survey-creator/docs
    cd packages/survey-creator
    npm run doc_gen
  displayName: 'Generate docs'


- task: CopyFiles@2
  inputs:
    SourceFolder: 'packages/survey-creator/build'
    targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorBuild/build
