trigger:
  batch: true
  branches:
    exclude:
    - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator
    npm install
    npm run build_prod
    npm run test_ci
    npm run testcafe_ci
  displayName: 'creator v1'
